alaminiy/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^toko/', include('toko.urls')),
    url(r'^profil/' ,include('profil.urls')),
] 
# if settings.DEBUG:
#     urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += patterns(
    #     'django.views.static',
    #     (r'^media/(?P<path>.*)',
    #     'serve',
    #     {'document_root': settings.MEDIA_ROOT}),
    #      )

    # urlpatterns += patterns('',
    #     url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  {
    #         'document_root': settings.MEDIA_ROOT,
    #     }, name ="mediaupload",),
    # )

profil/urls.py
from django.conf.urls import url
from profil import views

urlpatterns = [url(r"^$", views.profil, name="profil_view" ),
                url(r'^edit/$', views.profil_edit, name='profil_edit'),
                url(r'^api/$', views.profil_api, name='profil-api')
                ]

toko/urls.py
from django.conf.urls import url 
from toko import views

urlpatterns = ( url(r'^$', views.home_page, name="home_page" ),
                url(r'^barang/(?P<barang_slug>.+)/$', views.produk_detail, name="produk_detail"),
                url(r'^kategori/(?P<kategori_slug>.+)/$', views.kategori, name="kategori_barang"),
               )

profil/models.py
from django.db import models

# Create your models here.

class Profil(models.Model):
    nama = models.CharField(max_length=100)
    tagline = models.CharField(max_length=250)
    deskripsi = models.TextField()
    alamat = models.CharField(max_length=500)
    slug = models.SlugField(default="")

    def __str__(self):
        return self.nama

class Kontak(models.Model):
    pass

class SocialMedia(models.Model):
    profil = models.ForeignKey(Profil, default="", related_name="socialmedia")
    provider = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.provider

   



class Phone(models.Model):
    profil = models.ForeignKey(Profil, related_name="phone")
    nomor = models.CharField(max_length=20)
    TIPE_CHOICE = (
                   ("p", "primary"),
                   ("s", "secondary")
                   )
    tipe = models.CharField(max_length=1, choices=TIPE_CHOICE)

    def __str__(self):
        return str(self.nomor)

    def save(self, *args, **kwargs):
        phones = Phone.objects.all()
        phone_tipe = [p.tipe for p in phones]
        if self.tipe in phone_tipe:
            self.tipe = "s"
        super(Phone, self).save(*args, **kwargs)	

class Email(models.Model):
    TIPE_CHOICE = (
                   ("p", "primary"),
                   ("s", "secondary")
                   )
    profil = models.ForeignKey(Profil, related_name='email')
    alamat = models.EmailField()
    tipe = models.CharField(max_length=1, choices=TIPE_CHOICE)

    def __str__(self):
        return self.alamat

    def save(self, *args, **kwargs):
        emails = Email.objects.all()
        email_tipe = [e.tipe for e in emails]
        if 'p' in email_tipe:
            self.tipe = 's'
        super(Email, self).save(*args, **kwargs)

profil/forms.py
from django.forms import ModelForm, inlineformset_factory
from profil.models import Profil, Phone, Email, SocialMedia

class PhoneForm(ModelForm):
    class Meta:
        model = Phone
        fields = ('nomor', 'tipe')

    def __init__(self, *args, **kwargs):
        self.profil = kwargs.pop('profil')
        super().__init__(*args, **kwargs)

    def save(self):
        phone = super().save(commit=False)
        phone.profil = self.profil
        phone.save()
        return phone

class EmailForm(ModelForm):
    class Meta:
        model = Email
        fields = ('alamat', 'tipe')

    def __init__(self, *args, **kwargs):
        self.profil = kwargs.pop("profil")
        super().__init__(*args, **kwargs)

    def save(self):
        email = super().save(commit=False)
        email.profil = self.profil
        email.save()
        return email

class SocialForm(ModelForm):
    class Meta:
        model = SocialMedia
        fields = ['provider', 'url']

    def __init__(self, *args, **kwargs):
        self.profil = kwargs.pop('profil')
        super().__init__(*args, **kwargs)

    def save(self):
        social = super().save(commit=False)
        social.profil = self.profil
        social.save()
        return social

PhoneFormSet = inlineformset_factory(Profil, Phone, can_delete=False, fields='__all__',
                extra=1 )

class ProfilForm(ModelForm):
    class Meta:
        model = Profil
        exclude = ('slug',)

# class ProfilForm(forms.Form):
#     nama = forms.CharField(label="Nama", max_length=100)
#     tagline = forms.CharField(label="Tagline", max_length=250)
#     deskripsi = forms.CharField(label="Deskripsi", widget=forms.Textarea)
#     alamat = forms.CharField(label="Alamat", max_length=500)

profil/views.py
from django.shortcuts import render,redirect
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework import permissions, status
from profil.models import Profil
from profil.forms import ProfilForm, PhoneFormSet
from profil.serializers import  ProfilSerializer
# Create your views here.
def profil(request):
    profil = Profil.objects.first()
    return render(request, "profil/profil.html", {"profil":profil,
                  "profpage":True})

def profil_edit(request):
    profilfirst = Profil.objects.first()

    if request.method == 'POST':
        form = ProfilForm(request.POST)
        if form.is_valid():
            profil = form.save(commit=False)
            phone_formset = PhoneFormSet(request.POST, instance=profilfirst) 
            if phone_formset.is_valid():
                profil.save()
                phone_formset.save()
                return redirect('profil_view')
    else:
        form = ProfilForm(instance=profilfirst)
        phone_formset = PhoneFormSet(instance=profilfirst)
    context = {"form":form, 'phone':phone_formset}
    return render(request, "profil/profil_edit.html", context )

@api_view(['GET', 'PUT'])
@permission_classes([permissions.IsAuthenticatedOrReadOnly])
def profil_api(request):
    profil = Profil.objects.first()
    if request.method == "GET":
        serializer = ProfilSerializer(profil)
        return Response(serializer.data)
    elif request.method == "PUT":
        serializer = ProfilSerializer(instance=profil, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(serializer.errors, status=400)

templates/profil/head.html
<h1 class="text-uppercase">{{profil.nama}}</h1>
<h4 class="text-uppercase">{{profil.tagline}}</h4>

templates/profil/profil.html
{% extends "toko/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <!-- ini untuk bagian kiri, yaitu deskripsi dan alamat -->
        <div class="col-md-6 text-center">
            <div class="row">
                <div class="col-md-12">
                    <p>{{profil.deskripsi}}</p>
                </div>
            </div>
            <div class="row">
                <div class="row-md-12">
                    <p>{{profil.alamat}}</p>
                </div>
            </div>
        </div>
        <!-- judul, tagline, phone, social, email -->
        <div class="col-md-6 text-right">
            <div class="row">
                <div class="col-md-12">
                    <h1>{{profil.nama}}</h1>
                    <h4>{{profil.tagline}}</h4>
                </div>
            </div>
            <!--phone-->
            <div class="row">
                <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Phone</div>
                    <div class="panel-body">
                    <table class="table">
                    
                    {% for phone in profil.phone.all %}
                    <tr>
                    <td>{{ phone.nomor }}
                    {{ phone.get_tipe_display }}</td></tr>
                    {% endfor %}
                    
                    </table>
                    </div>
                </div>
                </div>
            </div>
            <!--social-->
            <div class="row">
                <div class="col-md-12">
                <div class="panel panel-default">
                <div class="panel-heading">Social Media</div>
                <div class="panel-body">
                <table class="table">
                    
                    {% for social in profil.socialmedia.all %}
                    <tr>
                    <td><a href="{{social.url}}">{{social.provider}}</a></td></tr>
                    {% endfor %}
                    
                    </table>
                    </div>
                    </div>
                    </div>
                </div>
                    <!--email-->
            <div class="row">
                <div class="col-md-12">
                <div class="panel panel-default">
                <div class="panel-heading">Social Media</div>
                <div class="panel-body">
                <table class="table">
                    
                    {% for email in profil.email.all %}
                    <tr>
                    <td><a href="mailto:{{email.alamat}}">{{email.alamat}}</a></td></tr>
                    {% endfor %}
                    
                    </table>
                    </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/profil/profil_edit.html
{% extends 'toko/base.html' %}
{% block content %}
<form action="{% url 'profil_edit' %}" method="post">
{% csrf_token %}
<table>
    {{form.as_table}}
    {{phone.management_form}}
    {{phone.as_table}}
</table>
<input type="submit" name='submit' value="submit" />
</form>
{% endblock %}