alaminiy/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^toko/', include('toko.urls')),
    url(r'^profil/' ,include('profil.urls')),
] 
# if settings.DEBUG:
#     urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += patterns(
    #     'django.views.static',
    #     (r'^media/(?P<path>.*)',
    #     'serve',
    #     {'document_root': settings.MEDIA_ROOT}),
    #      )

    # urlpatterns += patterns('',
    #     url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  {
    #         'document_root': settings.MEDIA_ROOT,
    #     }, name ="mediaupload",),
    # )

toko/urls.py
from django.conf.urls import url 
from toko import views

urlpatterns = ( url(r'^$', views.home_page, name="home_page" ),
                url(r'^barang/(?P<barang_slug>.+)/$', views.produk_detail, name="produk_detail"),
                url(r'^kategori/(?P<kategori_slug>.+)/$', views.kategori, name="kategori_barang"),
               )

toko/models.py
from django.db import models
from django.template.defaultfilters import slugify
from versatileimagefield.fields import VersatileImageField
# Create your models here.

class Kategori(models.Model):
    nama = models.CharField(max_length = 150,
                            unique = True)
    slug = models.SlugField(max_length = 200,
                            allow_unicode = True)

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = slugify(self.nama)
        super(Kategori,self).save(*args, **kwargs)

    def __str__(self):
        return self.nama

class Barang(models.Model):
    kategori = models.ManyToManyField(Kategori, blank=True)
    judul = models.CharField(max_length = 250)
    ikhtisar = models.TextField()
    harga = models.IntegerField(default=0)
    slug = models.SlugField(max_length = 300,
                            allow_unicode = True)

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = slugify(self.judul)
        super(Barang,self).save(*args, **kwargs)

    def __str__(self):
        return self.judul

class Atribut(models.Model):
    nama = models.CharField(max_length = 150)
    isi = models.CharField(max_length = 150)
    barang = models.ForeignKey(Barang)

    def __str__(self):
        return "%s : %s" %(self.nama, self.isi)

class Gambar(models.Model):
    image = VersatileImageField(upload_to = 'gambar_produk')
    barang = models.ForeignKey(Barang)

    # def __str__(self):
    #     return self.url

    

toko/views.py
from django.shortcuts import render

from toko.models import Barang, Kategori
from profil.models import Profil
# Create your views here.
def home_page(request):
    barang = Barang.objects.all().order_by("-id")[:4]
    profil = Profil.objects.get(slug="toko-al-aminiy")
    return render(request, "toko/home_page.html", {"barang" : barang,
                  "index":True, "profil":profil})

def produk_detail(request, barang_slug ):
    profil = Profil.objects.get(slug="toko-al-aminiy")
    produk = Barang.objects.get(slug=barang_slug)
    return render(request, "toko/produk_detail.html", {"barang" : produk,
                  "profil":profil})

def kategori(request, kategori_slug):
    profil = Profil.objects.get(slug="toko-al-aminiy")
    kategori = Kategori.objects.get(slug=kategori_slug)
    
    return render(request, "toko/kategori.html", {"kategori":kategori,
                  "profil":profil})

templates/toko/base.html
{% load staticfiles %}
{% load toko_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>Toko Al Aminiy {%block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

</head>
<body>
    
        <header id="masterheader" class="container-fluid">
            <nav id="top-nav" class="nav row">
                <div class="col-md-6">
                    <ul class=" nav nav-pills ">
                        <li><a href="https://m.facebook.com" class="fa fa-facebook"></a></li>
                        <li><a href="https://m.facebook.com" class="fa fa-instagram"></a></li>
                        <li><a href="https://m.facebook.com" class="fa fa-whatsapp"></a></li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <ul class="nav nav-pills navbar-right ">
                        <li><a href="{% url 'home_page' %}" >Home</a></li>
                        <li><a href="{% url 'profil_view'%}">Tentang</a></li>
                        <li><a href="">Kontak</a></li>
                    </ul>
                </div>
            </nav>
            <div class="row">
                <div class="col-md-12 text-center">
                    <a href="{% url 'home_page' %}" class="judul-halaman">
                    {% dapatkan_profil %}
                    </a>    
                </div>
                
            </div>
            <nav>
                <div class="navbar navbar-inverse">
                    <div class="">
                        <ul class="nav navbar-nav">
                            <li {% if index %} class="active" {%endif%}><a href="{% url 'home_page'%}">Home</a></li>
                            <li{% if profpage %} class="active" {%endif%}><a href="{% url 'profil_view'%}">Tentang</a></li>
                            <li><a href="">Blog</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Kategori <span class="caret"></span></a>
                                {% dapatkan_semua_kategori %}
                            </li>
                        </ul>
                        <div class="navbar-right" style="margin-right:10px;">
                            <p class="navbar-text"><b class="fa fa-whatsapp"></b> 0858-6761-6121</p>
                        <form class="navbar-form navbar-right">
                            <button type="submit" class="btn btn-default glyphicon glyphicon-search"></button>
                            <div  class="form-group">
                                <input class="form-control" type="text" placeholder="Cari Produk ?" >
                                </form>
                                </div>
                            </div>
                        
                        
                    </div>
                
            </nav>
        </header>
        {% block content %}
        {% endblock %}
        <footer>
            <div class="container-fluid"style="background-color:#333; color:white;">
                <div class="row" >
                    <div class="col-md-4" style="margin-top:15px;">
                        <ul>
                            <li><a href="">Home</a></li>
                            <li><a href="">Profil</a></li>
                            <li><a href="">Kontak</a></li>
                        </ul>
                        
                    </div>
                    <div class="col-md-4">
                        
                        <div class="col-md-4"><a href="https://m.facebook.com" class="fa fa-facebook"></a></div>
                        <div class="col-md-4"><a href="https://m.facebook.com" class="fa fa-instagram"></a></div>
                        <div class="col-md-4"><a href="https://m.facebook.com" class="fa fa-whatsapp"></a></div>
                    
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">Made by me [mihfazhillah@gmail.com]</div>
                </div>
            </div>
        </footer>
</html>

templates/toko/cat.html
{% if cats %}
    <ul class="dropdown-menu">
        {% for category in cats %}
            <li><a href="{% url 'kategori_barang' category.slug %}">{{category.nama|title}}</a></li>
        {% endfor %}
    </ul>
{% endif %}

templates/toko/home_page.html
{% extends "toko/base.html" %}
{% block content %}
{% load staticfiles %}
{% load toko_extras %}
<content>
<div class="container">
<div class="row">
    <div class="panel panel-hitam">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3>Paling Baru</h3>
            </div>
        </div>
    </div>
    <div class="row">
        {% for b in barang %}
    <div class="col-md-3 text-center align-center">
                    
                    <div class="panel-body">
                    
                    
                    {% with b.gambar_set.all|first as img %}
                    <img src="{{ img.image.crop.300x450 }}" alt="{{img.image.name}}" class="img-thumbnail img-rounded"  >
                    {% endwith %}
                    <a href="{% url 'produk_detail' barang_slug=b.slug %}">
                    <div class="caption">
                    <h5>{{ b.judul|title }}</h5>
                    <p>{{b.harga|currency}}</p>
                    </div>
                    </div>
                    </a>
                    
                
                </div>
                {% endfor %}
    </div>
</div>
</div>
</div>
</content>

{% endblock %}

templates/toko/kategori.html
{% extends "toko/base.html" %}
{% block title %}{{kategori.nama | title }}{% endblock %}
{% block content %}
{% load toko_extras %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center"><h3>{{ kategori.nama | title }}</h3></div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center center">
            <div class="panel panel-default">
                {% for barang in kategori.barang_set.all %}
                <div class="col-md-4">
                    <div class="panel-body">
                        {% with barang.gambar_set.all|first as img %}
                        <img src="{{img.image.crop.313x363}}" class="img-responsive img-rounded img-thumbnail">
                        {% endwith %}
                        <a href="{% url 'produk_detail' barang.slug %}">
                        <div class="caption">
                            <h4>{{barang.judul|title}}</h4>
                            <p>{{barang.harga | currency}}</p>
                        </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/toko/produk_detail.html
{% extends "toko/base.html" %}
{% block title %}{{barang.judul|title}}{% endblock %}
{% block content %}
{% load toko_extras %}
<div class="container">
    <!--judul-->
    <div class="row">
        <div class="col-md-12 text-center" style="margin-bottom:30px;">
            <h3>{{barang.judul | title}}</h3>
            <p class="text-danger">*klik gambar untuk memperbesar gambar</p>
        </div>
    </div>
    <!-- end judul -->
    <!-- gambar, detail dsb -->
    <div class="row text-center">
        <div class="col-md-6">
            <div class="panel panel-hitam">
                <div class="panel-heading">Ikhtisar</div>
                <div class="panel-body"><p>{{barang.ikhtisar}}</p></div>
            </div>

            <div class="panel panel-hitam">
                <div class="panel-heading">Harga</div>
                <div class="panel-body"><p>{{barang.harga | currency}}</p></div>
            </div>

            <div class="panel panel-hitam">
                <div class="panel-heading">Detail</div>
                <div class="panel-body">
                <table class="table">
                {% for detil in barang.atribut_set.all %}
                    <tr>
                        <td>{{ detil.nama|title }}</td>
                        <td>{{ detil.isi|title }}</td>
        
                    </tr>
                {% endfor %}
                </table>
                </div>
            </div>

            
            <div class="panel panel-hitam">
                <div class="panel-heading">Kategori Barang</div>
                <div class="panel-body">
                    {% for kategori in barang.kategori.all %}
                    <a href="{% url 'kategori_barang' kategori.slug %}" class="btn btn-primary btn-sm">{{kategori.nama|title}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-6" >
            <div class="col-md-12" style="margin-bottom:20px;">
                {% with barang.gambar_set.all|first as img %}
                
                <img src="{{img.image.thumbnail.250x300}}" class="img-responsive img-thumbnail" ></a>

                
                {% endwith %}
            </div>
            {% for img in barang.gambar_set.all %}
            <div class="col-md-4">
                <a href="#{{img.image.name}}" >

                <img src="{{ img.image.thumbnail.100x100}}" class="img-responsive thumbnail" data-toggle="modal" data-target="#{{img.id}}"></a>
                
            </div>
            <div class="modal fade" id="{{img.id}}">
                    <div class="modal-dialog modal-default" role="document" tab-index="-1">
                        
                        <div class="modal-content">
                            <div class="modal-header" data-dismiss="modal">
                                <h4 class="text-danger text-uppercase">Klik disini untuk close</h4>
                            </div>
                            <div class="modal-body">
                            <img src="{{img.image.thumbnail.500x600}}">
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}